from tkinter import *
from tkinter import messagebox
from mysql import connector
parent = Tk()
checkvar1 = IntVar() 
def database():
    conn = connector.connect(user = 'root', password = 'root', host = '127.0.0.1', port = '3306', database = 'form1')
    mycursor = conn.cursor()
    mycursor.execute("insert into form1 values(%s,%s,%s,%s,%s,%s)",(nameEntry.get(), uniRollNoEntry.get(), colRollNoEntry.get(), streamEntry.get(), semester.get(), checkvar1.get()))
    messagebox.showinfo("Info","Submitted")
    conn.commit()

nameLabel = Label(parent, text="Student Name").place(x= 10,y=20)
uniRollNoLabel = Label(parent, text="University Roll No.")
uniRollNoLabel.place(x= 10,y=60)
colRollNoLAbel = Label(parent, text="College Roll No.")
colRollNoLAbel.place(x= 10,y=100)
streamLabel = Label(parent, text="Choose Stream")
streamLabel.place(x= 10,y=140)
semLabel = Label(parent, text="Choose semester")
semLabel.place(x= 10,y=180)
feeLabel = Label(parent, text="Fee Paid")
feeLabel.place(x= 10,y=220)
submit = Button(parent, text='SUBMIT', command= database)
submit.place(x= 10,y=260)

nameEntry = Entry(parent)
nameEntry.place(x =150, y = 20)  
uniRollNoEntry = Entry(parent)
uniRollNoEntry.place(x = 150, y = 60) 
colRollNoEntry = Entry(parent)
colRollNoEntry.place(x = 150, y = 100)  
streamEntry = Entry(parent)
streamEntry.place(x = 150, y = 140)
semester = Spinbox(parent, from_= 1, to=8)
semester.place(x = 150, y = 180)
feeYes = Checkbutton(parent, text = "Yes", variable = checkvar1, onvalue = 1, offvalue = 0)
feeYes.place(x= 150,y=220) 
feeNo = Checkbutton(parent, text = "No", variable = checkvar1, onvalue = 0, offvalue = 1)
feeNo.place(x= 150,y=240)  
parent.mainloop()